language: c
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq build-essential libhiredis-dev libhiredis0.10
script: ./autogen.sh && ./configure && make && make check
compiler:
  - clang
  - gcc